apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ingestor-monitor
  name: ingestor-monitor
spec:
  endpoints:
  - interval: 5s
    port: management
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: ingestor

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: transformer-monitor
  name: transformer-monitor
spec:
  endpoints:
  - interval: 5s
    port: management
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: transformer
