{
 "title": "Booking Batch Processing Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Camel Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingestor Total Messsage",
   "type": "stat",
   "description": "Total message captured and sent to AMQ",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blog_braindose_demo_observability_message_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingestor Total Message Size",
   "type": "stat",
   "description": "Total Message Size Sent to AMQ",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blog_braindose_demo_observability_size_sum_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingestor Throughput",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blog_braindose_demo_observability_message_total / on() group_right() CamelRoutePolicy_seconds_sum{routeId=\"ingestor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total DB Inserts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blog_braindose_demo_observability_sql_total{module=\"total\",type=\"insert\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Deleted Records",
   "type": "stat",
   "description": "Total Deleted Records",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blog_braindose_demo_observability_sql_total{module=\"total\",type=\"delete\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inserts SQL Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blog_braindose_demo_observability_sql_total{module=\"total\",type=\"insert\"} / on() group_right() CamelRoutePolicy_seconds_sum{routeId=\"transformer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total DB Time",
   "type": "stat",
   "description": "Total time take to complete SQL inserts and deletes in seconds",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "CamelRoutePolicy_seconds_sum{routeId=\"transformer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Time per 1000 messages",
   "type": "stat",
   "description": "DB time in seconds taken to process inserts and deletes for eevery 1000 messages",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "CamelRoutePolicy_seconds_sum{routeId=\"transformer\"} / on() group_right() (blog_braindose_demo_observability_sql_total{module=\"total\",type=\"insert\"}/100000)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "GC Pause Count [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count[1m])",
     "legendFormat": "{{__name__}} - {{instance}}"
    }
   ]
  },
  {
   "title": "JVM GC Pause Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "jvm_gc_pause_seconds_sum", "legendFormat": "{{__name__}} - {{instance}}" },
    { "expr": "jvm_gc_pause_seconds_max", "legendFormat": "{{__name__}} - {{instance}}" }
   ]
  },
  {
   "title": "JVM Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    { "expr": "jvm_buffer_memory_used_bytes", "legendFormat": "{{__name__}} - {{instance}}" }
   ]
  }
 ]
}